import { AutopsyDetail, DecisionStreamItem, IncidentInfo, RailHealthCell } from "@/types";

export const initialRailGrid: RailHealthCell[] = [
  // HDFC Bank
  {
    bank: "HDFC Bank",
    method: "UPI",
    rail_id: "HDFC|UPI|RAZORPAY",
    state: "HEALTHY",
    error_rate_1m: 0.012,
    error_rate_5m: 0.014,
    error_rate_15m: 0.013,
    p95_latency_ms: 210,
    healthy_alternative: "ICICI|UPI|RAZORPAY",
  },
  {
    bank: "HDFC Bank",
    method: "CARD",
    rail_id: "HDFC|CARD|RAZORPAY",
    state: "HEALTHY",
    error_rate_1m: 0.018,
    error_rate_5m: 0.021,
    error_rate_15m: 0.019,
    p95_latency_ms: 450,
  },
  {
    bank: "HDFC Bank",
    method: "NETBANKING",
    rail_id: "HDFC|NB|RAZORPAY",
    state: "HEALTHY",
    error_rate_1m: 0.025,
    error_rate_5m: 0.024,
    error_rate_15m: 0.022,
    p95_latency_ms: 1200,
  },

  // State Bank of India
  {
    bank: "State Bank of India",
    method: "UPI",
    rail_id: "SBI|UPI|RAZORPAY",
    state: "DOWN",
    error_rate_1m: 0.884,
    error_rate_5m: 0.642,
    error_rate_15m: 0.412,
    p95_latency_ms: 4200,
    healthy_alternative: "HDFC|UPI|RAZORPAY",
  },
  {
    bank: "State Bank of India",
    method: "CARD",
    rail_id: "SBI|CARD|RAZORPAY",
    state: "DEGRADED",
    error_rate_1m: 0.142,
    error_rate_5m: 0.118,
    error_rate_15m: 0.082,
    p95_latency_ms: 1850,
    healthy_alternative: "ICICI|CARD|RAZORPAY",
  },
  {
    bank: "State Bank of India",
    method: "NETBANKING",
    rail_id: "SBI|NB|RAZORPAY",
    state: "HEALTHY",
    error_rate_1m: 0.031,
    error_rate_5m: 0.028,
    error_rate_15m: 0.029,
    p95_latency_ms: 1400,
  },

  // ICICI Bank
  {
    bank: "ICICI Bank",
    method: "UPI",
    rail_id: "ICICI|UPI|RAZORPAY",
    state: "HEALTHY",
    error_rate_1m: 0.009,
    error_rate_5m: 0.011,
    error_rate_15m: 0.010,
    p95_latency_ms: 195,
  },
  {
    bank: "ICICI Bank",
    method: "CARD",
    rail_id: "ICICI|CARD|RAZORPAY",
    state: "HEALTHY",
    error_rate_1m: 0.015,
    error_rate_5m: 0.016,
    error_rate_15m: 0.014,
    p95_latency_ms: 380,
  },
  {
    bank: "ICICI Bank",
    method: "NETBANKING",
    rail_id: "ICICI|NB|RAZORPAY",
    state: "HEALTHY",
    error_rate_1m: 0.020,
    error_rate_5m: 0.022,
    error_rate_15m: 0.021,
    p95_latency_ms: 1100,
  },

  // Axis Bank
  {
    bank: "Axis Bank",
    method: "UPI",
    rail_id: "AXIS|UPI|RAZORPAY",
    state: "HEALTHY",
    error_rate_1m: 0.014,
    error_rate_5m: 0.015,
    error_rate_15m: 0.017,
    p95_latency_ms: 240,
  },
  {
    bank: "Axis Bank",
    method: "CARD",
    rail_id: "AXIS|CARD|RAZORPAY",
    state: "HEALTHY",
    error_rate_1m: 0.022,
    error_rate_5m: 0.020,
    error_rate_15m: 0.019,
    p95_latency_ms: 410,
  },
  {
    bank: "Axis Bank",
    method: "NETBANKING",
    rail_id: "AXIS|NB|RAZORPAY",
    state: "DEGRADED",
    error_rate_1m: 0.165,
    error_rate_5m: 0.120,
    error_rate_15m: 0.088,
    p95_latency_ms: 2400,
    healthy_alternative: "HDFC|NB|RAZORPAY",
  },
];

export const activeIncidents: IncidentInfo[] = [
  {
    id: "inc_sbi_upi_outage",
    rail_id: "SBI|UPI|RAZORPAY",
    bank: "State Bank of India",
    severity: "DOWN",
    root_cause: "NPCI UPI Switch Core Banking Switch (CBS) Timeout - U30",
    started_at: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    affected_merchants: 48,
    money_at_risk_paise: 34285000,
    auto_rerouted_count: 312,
    active_mitigation: "Automated instant failover rerouting to HDFC & ICICI UPI rails",
  },
];

export const initialDecisionStream: DecisionStreamItem[] = [
  {
    id: "att_live_9482",
    merchant_id: "m_swiggy_ind",
    customer_id: "cust_90124",
    amount_paise: 185000,
    original_rail: "SBI|UPI|RAZORPAY",
    taxonomy_code: "ISSUER_OUTAGE",
    chosen_action: "SWITCH_RAIL",
    target_rail: "HDFC|UPI|RAZORPAY",
    bounds_status: "PERMITTED",
    expected_net_paise: 157250,
    created_at: new Date(Date.now() - 10000).toISOString(),
  },
  {
    id: "att_live_9481",
    merchant_id: "m_zomato_pay",
    customer_id: "cust_38192",
    amount_paise: 95000,
    original_rail: "HDFC|CARD|RAZORPAY",
    taxonomy_code: "NETWORK_TIMEOUT",
    chosen_action: "RETRY_IMMEDIATE",
    bounds_status: "PERMITTED",
    expected_net_paise: 77850,
    created_at: new Date(Date.now() - 25000).toISOString(),
  },
  {
    id: "att_live_9480",
    merchant_id: "m_zepto_quick",
    customer_id: "cust_51204",
    amount_paise: 420000,
    original_rail: "ICICI|UPI|RAZORPAY",
    taxonomy_code: "INSUFFICIENT_FUNDS",
    chosen_action: "RETRY_SCHEDULED",
    bounds_status: "PERMITTED",
    expected_net_paise: 327600,
    created_at: new Date(Date.now() - 40000).toISOString(),
  },
  {
    id: "att_live_9479",
    merchant_id: "m_blinkit_del",
    customer_id: "cust_11942",
    amount_paise: 145000,
    original_rail: "AXIS|CARD|RAZORPAY",
    taxonomy_code: "CARD_EXPIRED",
    chosen_action: "CUSTOMER_NUDGE",
    bounds_status: "PERMITTED",
    expected_net_paise: 98600,
    created_at: new Date(Date.now() - 65000).toISOString(),
  },
  {
    id: "att_live_9478",
    merchant_id: "m_swiggy_ind",
    customer_id: "cust_77218",
    amount_paise: 65000,
    original_rail: "SBI|UPI|RAZORPAY",
    taxonomy_code: "ISSUER_OUTAGE",
    chosen_action: "NO_ACTION",
    bounds_status: "REJECTED",
    expected_net_paise: 0,
    created_at: new Date(Date.now() - 90000).toISOString(),
  },
];

export const sampleAutopsyDetail: AutopsyDetail = {
  attempt_id: "att_live_9482",
  merchant_id: "m_swiggy_ind",
  customer_id: "cust_90124",
  amount_paise: 185000,
  created_at: new Date(Date.now() - 120000).toISOString(),
  raw_error_code: "U30",
  raw_error_message: "NPCI: Transaction timed out at remitter bank switch",
  payment_method: "UPI",
  rail_id: "SBI|UPI|RAZORPAY",
  taxonomy_code: "ISSUER_OUTAGE",
  taxonomy_confidence: 0.96,
  rail_sensing_state: "DOWN",
  cross_tenant_corroborated: true,
  corroborating_merchants_count: 34,
  actions_evaluated: [
    {
      action: "SWITCH_RAIL",
      probability: 0.88,
      gross_expected_paise: 162800,
      cost_paise: 75,
      friction_penalty_paise: 0,
      net_utility_paise: 162725,
      is_chosen: true,
      is_permitted_by_bounds: true,
    },
    {
      action: "RETRY_SCHEDULED",
      probability: 0.75,
      gross_expected_paise: 138750,
      cost_paise: 70,
      friction_penalty_paise: 0,
      net_utility_paise: 138680,
      is_chosen: false,
      is_permitted_by_bounds: true,
    },
    {
      action: "CUSTOMER_NUDGE",
      probability: 0.40,
      gross_expected_paise: 74000,
      cost_paise: 200,
      friction_penalty_paise: 200,
      net_utility_paise: 73600,
      is_chosen: false,
      is_permitted_by_bounds: true,
    },
    {
      action: "RETRY_IMMEDIATE",
      probability: 0.04,
      gross_expected_paise: 7400,
      cost_paise: 50,
      friction_penalty_paise: 0,
      net_utility_paise: 7350,
      is_chosen: false,
      is_permitted_by_bounds: true,
    },
    {
      action: "NO_ACTION",
      probability: 0.00,
      gross_expected_paise: 0,
      cost_paise: 0,
      friction_penalty_paise: 0,
      net_utility_paise: 0,
      is_chosen: false,
      is_permitted_by_bounds: true,
    },
  ],
  bounds_evaluation: {
    verdict: "PERMITTED",
    attempt_count: 1,
    max_attempts: 3,
    quiet_hours_active: false,
    customer_opted_out: false,
    contact_budget_remaining: 2,
  },
  ledger_proof: {
    entry_index: 48219,
    entry_hash: "7f4c9a81b308e5c462e3d9bb1148af037c2290f6c2f37c3580556f8f7c9e0123",
    previous_hash: "0a831e5b7218cf4193d258102d99aa567319e71e16f345c589b910fa4312ab45",
    merkle_root: "9c3e721a601248ef7820129a...",
    verified: true,
  },
};
