"use client";

import { Info, PowerOff } from "lucide-react";
import React from "react";
import { useApi } from "@/lib/useApi";
import type { LanguageStatus } from "@/types";

/**
 * Whether the language layer is switched on, asked once and shared by shape.
 *
 * `/v1/language/status` answers 200 even when the layer is disabled, which is
 * the whole reason it exists: "off" and "broken" call for different words on
 * the screen, and an endpoint that failed for both would make them look the
 * same. Off is stated calmly with the variable to set. Unreachable is stated as
 * an outage.
 */
export function useLanguageStatus() {
  return useApi<LanguageStatus>("/api/language/status");
}

export function LanguageDisabledNotice({
  status,
  unreachable,
}: {
  status: LanguageStatus | null;
  unreachable: boolean;
}): React.ReactElement {
  // Three outcomes, not two. "The layer is off" is a fact the status endpoint
  // reported; "the console never got a status" is not the same fact, and
  // rendering the first when the second happened is exactly the mistake this
  // console is built to avoid everywhere else.
  if (!unreachable && status === null) {
    return (
      <div className="rounded-xl border border-white/[0.07] bg-white/[0.035] p-4">
        <p className="flex items-center gap-2 text-xs font-semibold text-fg">
          <Info className="h-3.5 w-3.5 text-fg-faint" />
          The console could not read the language layer&apos;s status
        </p>
        <p className="mt-1.5 max-w-2xl text-[11px] leading-relaxed text-fg-muted">
          Something answered at salvage-brain&apos;s address and it was not{" "}
          <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono">/v1/language/status</code>.
          That is not evidence the layer is off, and not evidence it is on.
        </p>
      </div>
    );
  }

  if (unreachable) {
    return (
      <div className="state-down state-tile rounded-xl p-4">
        <p className="flex items-center gap-2 text-xs font-semibold text-down">
          <PowerOff className="h-3.5 w-3.5" />
          salvage-brain is unreachable
        </p>
        <p className="mt-1.5 text-[11px] leading-relaxed text-fg-muted">
          The console cannot tell whether the language layer is switched on. Start the stack with{" "}
          <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono">make up</code>.
        </p>
      </div>
    );
  }

  return (
    <div className="rounded-xl border border-white/[0.07] bg-white/[0.035] p-4">
      <p className="flex items-center gap-2 text-xs font-semibold text-fg">
        <Info className="h-3.5 w-3.5 text-fg-faint" />
        The language layer is switched off
      </p>
      <p className="mt-1.5 max-w-2xl text-[11px] leading-relaxed text-fg-muted">
        It is off by default, and a key already sitting in{" "}
        <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono">.env</code> does not switch it
        on — this is the only part of Salvage that makes an outbound call to a third party. Set{" "}
        <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono">
          SALVAGE_LANGUAGE_ENABLED=true
        </code>{" "}
        with a <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono">GEMINI_API_KEY</code>, and
        run <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono">make gemini-e2e</code> first
        to check the wire format against your key.
      </p>
      {status ? (
        <p className="mt-2 font-mono text-[10px] text-fg-faint">
          configured model: {status.model} · review queue:{" "}
          {status.review_queue_configured ? "configured" : "not configured"}
        </p>
      ) : null}
    </div>
  );
}

/** Provenance, shown under every generated artifact. */
export function Provenance({
  model,
  promptSha256,
  generatedAt,
}: {
  model: string;
  promptSha256: string;
  generatedAt: string;
}): React.ReactElement {
  return (
    <p className="mt-3 border-t border-white/[0.07] pt-2.5 font-mono text-[10px] leading-relaxed text-fg-faint">
      generated by {model} at {new Date(generatedAt).toLocaleString()} · prompt sha256{" "}
      <span title={promptSha256}>{promptSha256.slice(0, 16)}…</span>
      <br />
      A hosted model cannot be replayed to the same output, so this records what it was asked
      rather than pretending the answer can be reproduced. That is also why nothing here is
      allowed near a money decision.
    </p>
  );
}
