apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: PostgreSQL-Salvage
    type: postgres
    url: postgres:5432
    database: salvage
    user: salvage
    secureJsonData:
      password: salvage_dev_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    editable: false
